### ISSUE TITLE
论坛详情完善

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#100]
## 统计
<img width="767" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e027018b-36cb-4af5-994f-f6ddecf80cf9">

实装y一下

- [x] 已完成

**Comment by iRuxu** [comment]
## 点赞数回显

<img width="634" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9b6880c8-5c60-4501-ad23-28f15c63b4c0">

可以通过批量接口回显
见骚话列表页

- [x] 已完成

**Comment by iRuxu** [comment]
## 楼层交互增加图标

<img width="467" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/db1e2645-19b1-4a1b-83a4-6f6ec343de84">

<img width="247" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9d1403c9-8fc9-4c5d-9b7f-da27c4e5ef94">

- [x] 已完成

**Comment by iRuxu** [comment]
## 互动 - 黑洞

黑洞的原理，就是这个回复只有那个层主自己能看见，其它人则看不见了，包括管理！

请 @flyflyknife 回复接口到本处

前端注意增加tooltip：`拉入黑洞后仅层主自己可见`

权限：
+ 【楼主】或【具有manage_community权限的管理】或【超级管理group512】可以黑洞自己主题下的跟帖。
+ 【层主】或【具有manage_community权限的管理】或【超级管理group512】可以黑洞自己的楼层的评论。

前端请务必完成测试

- [ ] 已完成

**Comment by iRuxu** [comment]
## 删除

请确认删除的权限逻辑判断如上和黑洞一致。

@flyflyknife 

- [ ] 已完成

**Comment by iRuxu** [comment]
## 互动UI

<img width="1365" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/8d5027c3-fd8a-4da0-bf0d-2a81c9b6a5de">

- [x] 已完成

**Comment by iRuxu** [comment]
## 评论
<img width="616" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/0bb858c0-9840-491f-a4da-68e7659d89ac">

- [x] 已完成

**Comment by iRuxu** [comment]
## 重定向

当访问 /community/topic/65 时
自动跳转到 /community/65

- [x] 已完成

**Comment by iRuxu** [comment]
## 对自身互动
<img width="1776" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/b8337411-3021-4372-b761-11f88d325667">

- [x] 已完成

**Comment by iRuxu** [comment]
## 楼层-赞

<img width="438" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e7dd7874-6f34-4505-bb3e-38a3012e04de">

- [x] 已完成

**Comment by iRuxu** [comment]
## 打赏组件实装

![124000c3eb9211bed9325b1d074a046f](https://github.com/JX3BOX/bbs/assets/8476969/8f9c938f-9641-49a0-ae53-6f406c1faee4)

只有首层

- [x] 已完成

---

<img width="923" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/5fa619df-3274-4545-a2b4-64732a9281d5">
组件自带点赞 原先的点赞被我移除了，需要修改的话再调整

**Comment by iRuxu** [comment]
## 内容渲染
<img width="1031" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/4a1d89d0-246b-4d24-ba81-78f8b373e74a">

- [x] 已完成

---

> 饭团

现在只有楼主会用Article渲染（考虑会有茶馆迁移过来的帖子？ 怕有问题），别的都是用html渲染的，用户如果手输标签对的话，会转义，显示出标签对

**Comment by iRuxu** [comment]
## 权限
<img width="460" alt="image" src="https://github.com/JX3BOX/jx3box-common-ui/assets/8476969/516c1966-73d8-4408-84aa-2db5315c3b00">

- [x] 已完成

**Comment by iRuxu** [comment]
## 管理面板
<img width="742" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f2f2992c-e5c8-4199-8c78-e14ac39481f6">

可以提交category、title，有些场景可能要帮作者改 分类和标题

另外高亮需要接收具体的颜色值 

接口需要支持 @flyflyknife 

- [ ] 已完成

**Comment by iRuxu** [comment]
## 管理

<img width="976" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/78940c19-2ebd-4454-aa21-c3058e9ce5c0">

这个转为待审也没反应啊

- [x] 已完成

**Comment by iRuxu** [comment]
## 管理

<img width="623" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/cb266429-71c2-4d45-b093-2a351a6a1e11">

也可以改user_id

因为我们可能是让运营拿自己号发，然后我再改成公号id
因为现在我们的快速切换马甲功能还没上
就直接通过管理改

@flyflyknife 

- [ ] 已完成

**Comment by iRuxu** [comment]
## 编辑
<img width="1659" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/802a773c-dc6a-4ff3-ab16-f4acafd49349">

主楼的这个地址应该和顶部标题下面的链接一致

<img width="551" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/91fd9a65-a598-48e3-8b31-9e86029c4661">


- [x] 已完成

**Comment by iRuxu** [comment]
## 侧边栏
<img width="1207" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e9386ec3-60c5-45cf-8be0-fdd73410dae6">

- [x] 已完成

**Comment by iRuxu** [comment]
## 短消息

主题被回复，或回帖被评论，需要给短消息通知

@flyflyknife 

- [ ] 已完成

**Comment by iRuxu** [comment]
## 快速复制回复

<img width="378" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/fa938d85-83a7-4d62-bb2d-31c0fbb08741">

点击后，相当于回复一个一样的帖子

- [x] 已完成

**Comment by iRuxu** [comment]
## 论坛积累

回复一个帖子（不包含评论）
经验值+1，每日上限20点

@flyflyknife 

- [ ] 已完成

**Comment by iRuxu** [comment]
## 移动bug
<img width="200" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/01d0c4ad-9bf4-4e9b-a53d-3e3ce3aeb242">

- [x] 已完成

**Comment by iRuxu** [comment]
## 用户反馈
https://www.jx3box.com/community/83?page=1&onlyAuthor=false

- [x] 已完成

**Comment by iRuxu** [comment]
## 回帖

我直接在底部回帖后，需要刷新才能看见自己的回帖。应该直接插入的

- [x] 已完成

**Comment by iRuxu** [comment]
## 提交

<img width="1133" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/27f7f8ed-b667-453d-80b0-e4d3d20d0788">

- [x] 已完成

--- 

> 饭团

编辑的时候传了introduction参数 没更新掉这个字段  @flyflyknife

**Comment by iRuxu** [comment]
## META
<img width="323" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/0c7db9e8-83a2-45c8-b962-8370be84fbcc">

![8c55e88bd27109901e6494244d15878a](https://github.com/JX3BOX/bbs/assets/8476969/ff3aca75-c0d9-4343-bdc7-54d9385efcbc)


- [x] 已完成

--- 

帖子详情页的小册信息字段永远为null， 小册id返回正常，需要修复一下。
<img width="198" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/ff238100-4baa-4788-96be-2b27f50ae3ec">

**Comment by iRuxu** [comment]
## 侧边栏
<img width="533" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/2de76e59-2461-4f0e-9880-5fe47dab9a63">

怎么侧边栏自动显示出来了

- [x] 已完成

**Comment by iRuxu** [comment]
## 转述

<img width="1715" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/86612b94-783d-45b4-8346-abadf3e0bb39">

生成的内容不对
就是我说的，要按v-html来渲染

- [x] 已完成

**Comment by Moch1ce** [comment]
<img width="350" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/4376c1e5-2022-442c-841d-492700d67378">
我前面的帖子被我删掉了，这个楼层对不上了 @flyflyknife

**Comment by Moch1ce** [comment]
<img width="395" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/804d68e4-36af-4639-bafc-a6cda1157b10">

回帖我发送了一张图， 我看文档里回帖的接口有这个字段，但是回帖列表里的返回没有这个字段 @flyflyknife
