### ISSUE TITLE
论坛首页模块

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#105]
<img width="1265" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e53fd4f0-ef22-4a81-ac36-cd10684137b4">

在index库

- [x] 已完成

**Comment by Moch1ce** [comment]
<img width="517" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/3cf68ed8-b5ae-4a4d-8c5a-e54b5b2c9102">

这个字段需要更改吗

index库 文件路径 src/components/v3/community.vue  搜索关键字 index_lastest_artwork_click

**Comment by iRuxu** [comment]
<img width="1201" src="https://github.com/JX3BOX/bbs/assets/8476969/4adb3da8-4582-4de8-bc41-b73e8f5eb357">

@flyflyknife 另外给个接口

- [x] 已完成


---------------------------------

主题帖和回帖是分表的， 合在有一起取回的话，需要 一个明确的取回规则。

如果按日期排取的话，容易导致 某个主题的回帖占据全部内容区域。先定个数据拉取的规则把

**Comment by iRuxu** [comment]
取最新的主题和回复各4条吧。

**Comment by flyflyknife** [comment]
> 取最新的主题和回复各4条吧。

https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_GetMixLatest

**Comment by Moch1ce** [comment]
> > 取最新的主题和回复各4条吧。
> 
> https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_GetMixLatest


<img width="339" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/27f613f9-8cd7-4611-93fa-79136e522ff7">
回贴列表的content是空的 @flyflyknife

**Comment by flyflyknife** [comment]
> > > 取最新的主题和回复各4条吧。
> > 
> > 
> > https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_GetMixLatest
> 
> <img alt="image" width="339" src="https://private-user-images.githubusercontent.com/27264322/334249300-27f613f9-8cd7-4611-93fa-79136e522ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjQwNzgsIm5iZiI6MTcxNjg2Mzc3OCwicGF0aCI6Ii8yNzI2NDMyMi8zMzQyNDkzMDAtMjdmNjEzZjktOGNkNy00NjExLTkzZmEtNzkxMzZlNTIyZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAyMzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYmFjNTg4MWZhYjc1NjEzYzA0MDI5Njg1ZWUxMzAxYjQyYmI4NTgxODE2YmQ3OTdhYjIwNGJkMDkxZmE0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oeRr-E21fz1DMSCbmLqyA_0eAyExEEn1HBou-rGCky4"> 回贴列表的content是空的 @flyflyknife

已修复

**Comment by Moch1ce** [comment]
<img width="531" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/ac89414a-3d10-4d93-bb66-d351dac6ce1a">

这个帖子已经被转为待审核了，这里要筛选一下状态（大概） @flyflyknife 

- [x] 已完成
