### ISSUE TITLE
【论坛】管理更新banner_img

### ISSUE THREAD

**Issue by Kaviilee** [JX3BOX/bbs#109]
## 管理更新banner_img不成功

/api/next2/community/discussion/manage/topic/item/120/update 提交banner_img不成功

而且会导致原有的banner_img变成空

- [x] 已完成

**Comment by iRuxu** [comment]
## 管理接口导致小册丢失

### 第一步：作品ID113
<img width="1" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/d1ec3469-bd1b-4d82-8261-5d205f3ee6e3">

### 第二步：随便设置一个tag
<img width="1918" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f0f5b1b3-7122-4fc6-b300-25a1d770f464">

### 第三步：似乎会请求2个接口
<img width="1498" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/6a40f2a3-1f7a-48e4-8190-302a825c9cfe">

<img width="1233" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/0a0c78e3-73ed-4204-9d41-55490098a1ee">

### 第四步：结果就没有小册信息了
<img width="1062" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/125b8b46-892f-4d24-a6ee-ffd97cc2c7ce">


- [x] 已完成

**Comment by iRuxu** [comment]
## 帖子

我们之前有将文章移动到论坛这个功能
需要对这个接口加一个短消息。

### 消息模板
source_id | source_type | type | subtype | content 
---|---|---|---|---
$community_post_id | community | community | community_transfer  |  你的帖子已被转移至论坛

- [x] 已完成

**Comment by iRuxu** [comment]
## 接口
增加查询个人的全部公开正常的帖子，需要分页。
用于个人主页。

- [x] 已完成

---------------------

https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_GetPublicTopicList

在这个接口中增加 一个 `user_id=xxx` 查询参数即可满足要求
