### ISSUE TITLE
标签优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#112]
## 后台

<img width="1403" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9e650873-6dcd-400c-80a6-d80d2bbf7b8e">

- [x] 后端&后台已完成

**Comment by iRuxu** [comment]
## 前台

<img width="427" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/35c57dec-bd98-4246-95fb-7306c7716ec4">

那个标记改为是标记开关开的时候显示

- [x] 前端已完成

**Comment by iRuxu** [comment]
## 论坛互动

<img width="985" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/8cfbd2a2-59c9-43fd-96d2-ab18c8f19bc5">

以上功能只针对 ”楼层“，不针对”评论“。
评论保持不变。

这个答谢，其实就是和作业模式那里的一模一样
管理可以品鉴或打赏
其他人，则只可以打赏
对应的key叫 https://github.com/JX3BOX/jx3box-pay/issues/155  `community_topic_reply`

<img width="1917" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e6396df6-6669-48b8-b685-040752ef77e7">

帖子右上角参考评论显示被答谢了多少

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1465" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/97fd5f0f-6b04-495a-bc59-0b20d3a709a0">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="965" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/b17dc245-2193-4c25-86d2-7207c7aed339">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="776" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/978fd3d9-7160-4319-8c6e-7857a71ebc7d">

小册支持论坛

- [x] 已完成

**Comment by zixuan1986** [comment]
魔卡背景图以右上角为坐标原点适配

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="696" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/248d7f83-817d-4c44-85ce-298d10b2dc97">

- [x] 已完成
