### ISSUE TITLE
论坛若干优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#113]
<img width="401" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/a9bad3ab-8412-450c-a4f7-c57ef2b544e4">

下拉菜单这里，和默认菜单的样式基本一致，不要带图标
另外hover展示下拉，不要点击展示吧

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1682" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/84af90ca-cbd3-47bf-b91e-76b8400417b8">

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="1636" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/5f315742-57bc-4849-88c9-b990345f1683">

魔卡兼容问题

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="834" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/97053c47-8382-47b9-83b1-353a15e50040">

- [x] 已完成

**Comment by iRuxu** [comment]
每个魔卡 指定一个配套的主题色。
也就是说。
标题颜色，和边框颜色，用你们指定的颜色，这样让卡片看起来协调一些。
缺省就原来的黑色。
当用了魔卡的时候，hover的时候标题不要变色了

- [x] 已完成

**Comment by zixuan1986** [comment]
魔卡背景以右上角为坐标原点适配

- [x] 已完成

卡片hover阴影随卡片基色改变（可做可不做）

**Comment by zixuan1986** [comment]
创建帖子时默认分类为求助，但编辑帖子应该根据本身帖子的分类选择tab
![image](https://github.com/JX3BOX/bbs/assets/40552272/8438f382-b96b-43fa-a3f4-4b2582801ecb)
已有魔卡不再显示  “  你还没有任何魔卡，[点击前往]使用积分兑换。“
- [x] 已完成

**Comment by zixuan1986** [comment]
商城列表需要添加一个鼠标hover的展示效果
![image](https://github.com/JX3BOX/bbs/assets/40552272/624c282e-1ae2-4acd-a29e-2d54562e62e3)

 - [x] 已完成

**Comment by zixuan1986** [comment]
点标签返回对应的版块首页
![image](https://github.com/JX3BOX/bbs/assets/40552272/20400bf9-9bee-4feb-8dbe-abb86bcb74ea)

- [x] 已完成
