### ISSUE TITLE
剑三表情

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#19]
## 列表页
views/emotion.vue

各种互动项可参考骚话。
接口与骚话基本是一致的。除了发布更新。
接口见：https://cms.jx3box.com/api/cms/documentation

1. 顶部搜索框；并增加一个快捷发布框。✔️
2. 中间列表（考虑瀑布流）✔️
3. 列表项：
    3.1 图片缩略图，点击展开画廊浏览 ✔️
    3.2 点赞按钮
    3.3 精选标记，管理快捷加星按钮 ✔️
    3.4 原创标记 ✔️
    3.5 作者头像+昵称 ✔️
    3.6 描述文字，最多2行，点击进入单页 ✔️
4. 底部【加载更多】按钮
5. 同时保留分页 ✔️

**Comment by iRuxu** [comment]
## 加星推荐
PUT /api/cms/post/emotion/{id}/star

**Comment by iRuxu** [comment]
## 详情页
类似骚话，点击进入单个路由

1. 图片居中显示，最大尺寸800px
2. 图片下方展示图片描述
3. 描述下方显示一个按钮组【PNG】【GIF】，当图片已经是gif时无需展示
4. GIF帮助描述（我补）
5. Thx组件

**Comment by Kaviilee** [comment]
> ## 详情页
> 类似骚话，点击进入单个路由
> 
> 1. 图片居中显示，最大尺寸800px
> 2. 图片下方展示图片描述
> 3. 描述下方显示一个按钮组【PNG】【GIF】，当图片已经是gif时无需展示
> 4. GIF帮助描述（我补）
> 5. Thx组件

------
3，4 未完成

**Comment by iRuxu** [comment]
## 增加Type支持
增加type字段，存储门派ID，与骚话栏目保持一致
- [x] 发布中心
- [x] 前端筛选

**Comment by iRuxu** [comment]
## 增加快捷发布
同样需要在列表页增加快捷发布（只发单个图）
- [x] 已完成

**Comment by iRuxu** [comment]
## 快捷发布优化

![image](https://user-images.githubusercontent.com/8476969/145712719-92dce510-490f-4453-bbdd-c0a551d960fd.png)
发布按钮放到右侧，左侧下方增加 type，author，original等，参考发布中心
未登录用户处理逻辑亦同
不用传递type进组，每次都由用户自选

- [x] 已完成

**Comment by iRuxu** [comment]
## 列表页点赞优化
![image](https://user-images.githubusercontent.com/8476969/145712792-a73b9ddd-66f1-47a9-8723-5045429f62b9.png)
显示点赞心心与当前点赞数，完全参考骚话即可

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑操作栏
![image](https://user-images.githubusercontent.com/8476969/145712839-d93a075d-9e73-4467-a14d-5f273910a7c1.png)
设为精选，删除。
两个使用文字版，独立一行，完全参考骚话即可。
【补充】：在单页删除后应退回到list页

- [x] 已完成

**Comment by iRuxu** [comment]
## 瀑布流高度渲染问题
直接刷新页面正常，从其他路由切过来时会有异常
![image](https://user-images.githubusercontent.com/8476969/145713917-24f9bf95-e521-4c55-80e7-c73386f11724.png)

- [x] 已完成

**Comment by iRuxu** [comment]
## 点赞优化
1. 骚话栏目会请求2次点赞统计 
![image](https://user-images.githubusercontent.com/8476969/145718490-28194327-097f-404b-89bf-f55f870626fa.png)

2. 表情栏目的表情统计，注意在append时，不要重复请求已有的项目

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/145725145-315826b4-9ec8-4475-93eb-b0858f1fc8fd.png)

单页下加精状态判定问题

- [x] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/145760160-f41a289d-c09a-466f-ae2c-de070546698a.png)
列表页的精选状态，也有点混乱

- [x] 已完成

**Comment by iRuxu** [comment]
目前渲染瀑布流时（加载其实很快），渲染期间很久，用户没有感知，也应该保持loading状态
要等全部渲染完再去除loading

- [x] 已完成

**Comment by iRuxu** [comment]
## 瀑布流渲染报错
### A.复现步骤：1点击只看精选，2点击只看原创
![image](https://user-images.githubusercontent.com/8476969/145856856-c5a1c824-6e3a-4d00-86ae-51b20bbcda30.png)
有时候直接点“只看精选”也有这个bug

### B.只看原创没生效
点击只看原创，接口数据正常，但没有任何渲染

### C.有时候先点一下只看原创，再取消，不正常渲染瀑布流
接口是正常，需要重新刷新页面


- [ ] 已完成

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/146130684-5a5b5963-0ce1-4c54-88ee-a5a5bde0b0ab.png)

骚话列表页点击设为精选时，在当前条目前也立马显示一下加星图标

- [x] 已完成
