### ISSUE TITLE
剑三考试统计接口请求多次

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#24]
![image](https://user-images.githubusercontent.com/8476969/147743336-2c9d6f14-1d5f-4841-bcec-45b739e27e20.png)
两次get请求统计，一次带了cookie，一次没带。
因保留一次即可。

另check子璇exam代码最终版。

**Comment by Kaviilee** [comment]
@iRuxu 一次请求时thx组件的请求，一次是考生数的请求，没法删减
