### ISSUE TITLE
考试分数异常

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#34]
https://www.jx3box.com/exam/paper/72
只做最后1题，选D

https://www.jx3box.com/exam/paper/73
只做最后1题，选B

当只答对了最后一个，却是100分，不正常

**Comment by flyflyknife** [comment]
<img width="754" alt="图片" src="https://user-images.githubusercontent.com/68375170/172390120-25dc1806-b329-49b4-9bc4-b3d67fdcaed4.png">

**Comment by flyflyknife** [comment]
<img width="1363" alt="图片" src="https://user-images.githubusercontent.com/68375170/172390616-c9841201-9c4f-41bd-9dcd-bb1fb0e2263f.png">
