### ISSUE TITLE
小册

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#72]
## 简要提醒

+ 检查所有接口，都按新的规范来（包括路由规范、缓存逻辑等）
+ 其中，用户读取自己的小册的时候，应该增加一个/raw接口，不应该使用缓存
+ 注意：用户更新自己的作品时，应该删除原来的缓存
+ 注意：编辑自己作品时，权限的检查，

后面我会细化

- [x] 已了解

**Comment by iRuxu** [comment]
## 接口1
管理的地址从`/post/manage`变成了`/manage/post`
前端bbs库涉及的管理操作的地方需要修改

- [ ] 已完成

**Comment by iRuxu** [comment]
## 创建

前端位置：https://www.jx3box.com/publish/#/collection

包含1个创建接口

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑
前端位置：https://www.jx3box.com/publish/#/collection

包含1个更新接口，1个读取自己的接口

### 注意逻辑
+ 用户读取自己的小册的时候，应该增加一个/raw接口，不应该使用公共缓存的单查接口
+ 用户更新自己的作品时，应该删除原来的缓存，插件可配置
+ 编辑自己作品时，权限的检查，自己或editor+都可以

### Bug
如果先输入文章，没有选分类会异常

- [x] 已完成

**Comment by iRuxu** [comment]
## 我的列表与删除

前端位置：https://www.jx3box.com/publish/#/bucket/collection

包含1个我的列表接口（无缓存），1个删除接口。

### Bug
现在删除有问题，点击删除按钮，即使取消了，也会删除！离谱

- [x] 已完成

**Comment by iRuxu** [comment]
## 公开列表

前端位置：https://www.jx3box.com/collection

包含1个公开列表接口（有缓存）

### 注意逻辑
+ 默认只显示公开的

- [x] 已完成

**Comment by iRuxu** [comment]
## 公开详情

前端位置：https://www.jx3box.com/collection/31

包含1个公开详情接口（有缓存）。

### 注意逻辑
+ 注意注意，这里不会去做权限判断，就是所谓的公开或私有，只是会影响列表的出现，而单个查询，永远都是公开的。


### 前端补充
<img width="525" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/a997c861-2a2b-41a1-8a64-0010ab2437de">

- [x] 已完成

**Comment by iRuxu** [comment]
## 调用小册
https://www.jx3box.com/bbs/57715

<img width="514" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/4fea207b-fc6e-434e-a5ed-b5baa736c817">
<img width="299" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/3147ad38-7bf9-468e-9411-759e7d50bccb">

注意以上2个位置的接口调用了最新的上面楼层的接口。

- [x] 已完成

**Comment by iRuxu** [comment]
## 文档更新

小册指南更新 https://www.jx3box.com/tool/20891

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 我的列表与删除
> 前端位置：https://www.jx3box.com/publish/#/bucket/collection
> 
> 包含1个我的列表接口（无缓存），1个删除接口。
> 
> ### Bug
> 现在删除有问题，点击删除按钮，即使取消了，也会删除！离谱
> 
> * [x]  已完成

离谱也是臭宝你写的

**Comment by iRuxu** [comment]
## 编辑小册
<img width="887" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/5eaf0b60-2e1a-4ae9-848e-0a7bb889eb70">

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 编辑小册
> <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/8476969/289649421-5eaf0b60-2e1a-4ae9-848e-0a7bb889eb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDk5NjksIm5iZiI6MTcwMjM0OTY2OSwicGF0aCI6Ii84NDc2OTY5LzI4OTY0OTQyMS01ZWFmMGI2MC0yZTFhLTRhZTktODQ4ZS0wYTdiYjg4OWViNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDI1NDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk4MDlhMzZjMDk3OWY4MmI4OWJjZDdmMThkNmFkNDU4OTlmNjcxMTYyMjRmYzYyNzdhM2JiY2FjNDJhMTdjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Mqoviug4-gb8bIRUsjQzPjL64AUcKQw-icavjHRYjgE">
> * [ ]  已完成
很多旧数据是在这三个类型之外的，如果编辑也是这三个，那么旧数据就没法匹配到类型了

**Comment by iRuxu** [comment]
<img width="707" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/c6dece4d-93ef-4d1c-a10a-601663833c6c">

- [ ] 已完成
