### ISSUE TITLE
魔盒论坛优化2 - L

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#91]
### 接口实装
<img width="1313" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/ea8493f4-9066-46f2-aae2-f2ccf9faa475">

### 整体布局适配

![943ef6debd76261c132ea843f0a7acac](https://github.com/JX3BOX/bbs/assets/8476969/792a7fa4-984d-47ac-95ee-4298aac980b2)

- [x] 已完成

**Comment by iRuxu** [comment]
## 列表项 - 类型
<img width="456" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/d13de29f-4e2e-485f-93ae-45c94273c3b8">

使用标签，颜色先random马卡龙

- [x] 已完成

**Comment by iRuxu** [comment]
## 列表项 - 时间处理

<img width="167" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/bde283bc-1525-4101-8a4d-c132f98480a6">

<img width="316" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/1270e29a-4cff-4644-9771-be718212646b">

<img width="522" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/8e4114db-a3c5-4e5e-b160-08648e8b6e38">

<img width="268" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/eacca7b3-5fa5-4808-b133-e8644937c947">


- [x] 已完成

**Comment by iRuxu** [comment]
## 列表项 - meta样式

<img width="294" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/da4578b7-d254-4769-8f94-87c0c523dac7">

- [x] 已完成

**Comment by iRuxu** [comment]
## 列表项 - 关联小册

<img width="477" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f05764ca-678b-4576-9a0f-07a9c6dc3aae">

- [x] 已完成

**Comment by iRuxu** [comment]
## 列表项 - mark
![1ddede826bd2c68fc601acefb91dc95c](https://github.com/JX3BOX/bbs/assets/8476969/16e6b4b3-24cb-4c46-adaf-b5453f53a250)

待定，看群

- [x] 已完成

**Comment by iRuxu** [comment]
## tags

<img width="625" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/836f7e62-c21c-45d1-ab01-7d22b995de58">

到时候先跑一段时间，一些自动tag会通过openai来生成，等我先看看

- [x] 已完成

**Comment by iRuxu** [comment]
## 小册
<img width="351" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/fbdfe033-9b0d-4956-8965-193186602d0d">

- [x] 已完成

**Comment by iRuxu** [comment]
## 作者
<img width="366" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9bde9802-ba19-41f3-b06e-cd11eebeca64">

- [x] 已完成

**Comment by iRuxu** [comment]
## 分类筛选
<img width="1335" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/4234e2c1-81f4-4ee5-8f6f-b4bf2dfe11eb">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="815" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/62f519b6-996b-4170-974f-ffac8bec3baa">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="855" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/2d14bb19-54db-4d99-945d-6a3f21802661">

vue2不支持`?.`

- [x] 已完成

**Comment by iRuxu** [comment]
## 客户端

在发布页，还是添加上客户端的选择，默认值和现在逻辑不变，只是多一个`全端`可以选择

- [x] 已完成

**Comment by iRuxu** [comment]
## 发布按钮

<img width="346" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/d6c35603-6425-4dad-88a3-ff1bfec9e138">

等设计给图，放在img/community/publish.png中

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签优化


### 前置
先阅读 https://github.com/JX3BOX/os/issues/168

### 备注
hover时，显示 remark作为title（不作为tooltip）

- [x] 已完成

### 项目
取sort < 20的部分，按sort正序展示即可

- [x] 已完成

### 更多
<img width="1023" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e38260b7-17e6-4896-8865-f108d601d502">
这个更多项，直接html写在template即可。
展示sort>20的部分
下拉查看。
没有的时候，则disabled掉

- [x] 已完成


### 标记
等设计给资源，增加对应mark图标

- [x] 已完成

**Comment by iRuxu** [comment]
## 置顶

<img width="1526" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/afd6305e-7eb8-4b82-a24a-817cbf6ee828">

当没有置顶帖的时候，就第一个使用置顶样式

- [x] 已完成

**Comment by iRuxu** [comment]
## 类型

<img width="152" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/195d55f6-3803-4fcf-a4a4-968c3874db70">

使用前面的颜色 + 图标。

图标放置在本地img/community/category中，字符串和文件名对应

- [x] 已完成

**Comment by iRuxu** [comment]
## 时间图标

<img width="121" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e26d82d5-29a6-44a4-a07e-cfa9a746c2ae">

【刚刚】用`el-icon-loading`
【其它的可读时间】用`el-icon-time`
【具体日期时间】用`el-icon-date`

- [x] 已完成

**Comment by iRuxu** [comment]
## 分页

<img width="987" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e6d669c5-4cb9-4971-ae9b-544460c35a45">


到了最后一页应该隐藏，显示为灰色12px小字`没有更多了`

- [x] 已完成

**Comment by iRuxu** [comment]
## 顶部标签
<img width="205" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9d36e3ca-475e-489a-82e9-2e2d700d4c9a">

<img width="495" alt="f1926de2a892601c84bdfc82815b29b7" src="https://github.com/JX3BOX/bbs/assets/8476969/f38232ac-2d5a-40a0-a94e-faaa4eaf10fb">

样式似乎没完全按要求来

## 列表标签
<img width="975" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/37acb787-1c40-458e-aa70-85a34b2ad763">


- [x] 已完成

**Comment by Moch1ce** [comment]
> ## 顶部标签
> <img alt="image" width="205" src="https://private-user-images.githubusercontent.com/8476969/327926196-9d36e3ca-475e-489a-82e9-2e2d700d4c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjE3NzIsIm5iZiI6MTcxNDgyMTQ3MiwicGF0aCI6Ii84NDc2OTY5LzMyNzkyNjE5Ni05ZDM2ZTNjYS00NzVlLTQ4OWEtODJlOS0yZTJkNzAwZDRjOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMTExNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTMxYWE1NWZkNjdhNGZiYjkyNTM5NjE4MjU3YjBmODEwOTgzZGQ0YjJiOTY1YTExMDFjODA0NDM3NmQ3Y2M5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SFRIeDHebK23o345mhPcG2tfmDIJPYTH9F2wYhk11gQ"> <img alt="f1926de2a892601c84bdfc82815b29b7" width="495" src="https://private-user-images.githubusercontent.com/8476969/327926286-f38232ac-2d5a-40a0-a94e-faaa4eaf10fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjE3NzIsIm5iZiI6MTcxNDgyMTQ3MiwicGF0aCI6Ii84NDc2OTY5LzMyNzkyNjI4Ni1mMzgyMzJhYy0yZDVhLTQwYTAtYTk0ZS1mYWFhNGVhZjEwZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMTExNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdkMjYyZGU5MjZhMjIxNTE5Y2UzYTY2OWY4YzJkZTMyOTEyOTFiNzc0ZTZlNjdhNDI3OGM4ZDU3MjllOTdhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0OSbK9r-_zKu9W5IUn7ATKhMGEpY9wn0rhtd5Ufl5fs">
> 样式似乎没完全按要求来
> 
> ## 列表标签
> <img alt="image" width="975" src="https://private-user-images.githubusercontent.com/8476969/327926789-37acb787-1c40-458e-aa70-85a34b2ad763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjE3NzIsIm5iZiI6MTcxNDgyMTQ3MiwicGF0aCI6Ii84NDc2OTY5LzMyNzkyNjc4OS0zN2FjYjc4Ny0xYzQwLTQ1OGUtYWE3MC04NWEzNGIyYWQ3NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDRUMTExNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVhZDU0ZjYxNjU3MTE2NTMzYzU0MjNhMjU1MTU0ZTUzNjExMjE1MGVlNzViYWIxMDY2NmM0MjVjNDRiNzJhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k5aG-nU0mY9hR4g0aygj9ab9TM0HQkrWOJtQ-18w9XU">
> * [ ]  已完成
这个是我测试的时候选的全是拜师 是对的

**Comment by iRuxu** [comment]
## 标签 - 1
<img width="430" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e7874e79-b6b4-4574-962a-8845c63c10da">

这里设计师的意思是，这个类型都是援助类型
不是要文字改成援助啊。
文字不变啊。

- [ ] 已完成

**Comment by iRuxu** [comment]
## 标签- 2 
<img width="714" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/04a2b0e7-1fa2-4e52-9a8f-c2d12e39252d">

单词错了

装插件
<img width="277" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/0e86b5ee-5a18-4097-9986-b05c062c4190">

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签 - 1

<img width="636" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e076a1c3-1284-4bc0-b2c0-8a4e57c67fbb">

当存在标记时，使用hover的样式

但不影响选中时的样式

警示的颜色并未按设计稿的来

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签 - 3 
<img width="386" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f5b6047d-1fc7-4fa0-9ca6-299c74ff7032">

disabled的项  50%透明度

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签 - 4

<img width="418" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/bee30d96-a2b8-4903-a5e6-0c8310cf38e1">

现在所有tie'z帖子都是拜师？？
那就建个别的

实装正确的category并同步样式颜色

- [x] 已完成

**Comment by iRuxu** [comment]
## 封面缩略图

<img width="506" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/d6317afd-51fe-4ef0-a03c-f6d79fa3df69">

<img width="659" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/c7871bae-5f28-460d-9847-d56a0d7f89d5">

要区分置顶位置的大小

- [x] 已完成

**Comment by iRuxu** [comment]
## 发布校验
<img width="699" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/746bcaeb-c8ad-4810-b5a6-695a02c8e95d">

- [x] 已完成

**Comment by iRuxu** [comment]
## 摘要
<img width="663" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/ec84cf19-b1cc-4f85-84a0-07d39f0716c0">

- [x] 已完成

**Comment by iRuxu** [comment]
## 作者
<img width="782" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/c298c6f7-a83d-4579-a8ee-171223f4e2e6">

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签 - 5
<img width="286" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/fb139d68-2a18-4589-83a4-ef9df8b2d980">

- [x] 已完成

**Comment by iRuxu** [comment]
## 标签 - 6
<img width="1384" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/a71067ac-11c9-4fa0-87f2-ffd8f4ca4e52">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="643" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/e6fd4292-5081-4a55-98a9-e5a10bf8e4d7">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="568" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/57d9b9e2-31d6-4f4c-b3fa-186c50619b77">

- [x] 已完成
