### ISSUE TITLE
魔盒论坛优化4 - R

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#93]
## 初版

详情页实装接口

确认楼层效果。

扩展功能也需要实装

- [ ] 已完成

**Comment by Moch1ce** [comment]
现在的评论接口我接了一下 无法完成嵌套效果，你看看接口需要改动嘛。

<img width="496" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/55e6a1ee-d207-4bd6-95d6-66bc3bbc0867">

@flyflyknife
