### ISSUE TITLE
论坛优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#94]
<img width="545" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/1fd65ed0-eec2-4ba1-99f7-a6796a938986">

- [x] 已完成

-------------

https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E7%AE%A1%E7%90%86%E5%91%98-%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_ManagerOpt

**Comment by iRuxu** [comment]
## 小册

<img width="672" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/021ff4be-d915-452c-95e4-ea959198b96a">

表是jx3box库的post_collections表

- [x] 已完成

**Comment by iRuxu** [comment]
## 废弃
<img width="469" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/8132f0a4-3dd3-4304-a84d-a5c108f513fd">

没啥用。

就用一个category就可以

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="749" alt="企业微信截图_18eabe2b-36a5-4695-bf60-3c1e4b301433" src="https://github.com/JX3BOX/bbs/assets/8476969/40c9894e-c53c-4d75-aff9-5c7826895062">

- [x] 已完成

**Comment by flyflyknife** [comment]
![image](https://github.com/JX3BOX/bbs/assets/68375170/5d0495ce-bce8-4212-ad10-2801b37b2ab8)
