### ISSUE TITLE
魔盒论坛优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#95]
## 列表头条
<img width="911" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/41094d49-17f5-48c0-9f43-3df7dee8cf0a">

<img width="875" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/6476cebf-a8e3-4fa9-a510-c81a448d32e8">

注意尺寸也保持一致

- [x] 已完成

**Comment by iRuxu** [comment]
## 分类导航
<img width="568" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/57d9b9e2-31d6-4f4c-b3fa-186c50619b77">

- [x] 已完成

**Comment by iRuxu** [comment]
## 详情标题
<img width="843" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/b13759b1-45c1-42db-9c9b-90b998b7c006">

<img width="454" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/afe4b3cf-10ca-4aa2-9f9f-858bb79b060d">


- [x] 已完成

**Comment by iRuxu** [comment]
## 回复嵌套异常


http://localhost:8081/community/65

<img width="953" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/edfac4f0-e33a-4e8a-a7f8-602858f17bbd">

无法正常楼中楼回复

@flyflyknife 

- [x] 已完成


------------------------------


请确定数据以及接口路径正确

![图片](https://github.com/JX3BOX/bbs/assets/68375170/6efc58d7-d741-497d-a6ab-691a0cd92b72)

**Comment by iRuxu** [comment]
## 主楼互动-1

<img width="1760" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/458c2615-26c6-4f3f-ab40-35b84a13cba6">

- [x] 已完成

**Comment by iRuxu** [comment]
## 主楼互动-2

<img width="242" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/29028a63-3432-4803-a8a9-f211b3a6e5c8">

点赞没有实装。
这个有现成的接口，

参考文章的公共组件

<img width="596" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f824e9de-2a9f-4eb3-bd83-6e22c143e31a">

- [x] 已完成

**Comment by iRuxu** [comment]
## 楼层互动UI

<img width="618" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/dd447ee9-882b-4850-8a40-cd2d1e784983">

看设计稿的间距

注意互动按钮均只有登录用户可见User.isLogin()

- [x] 已完成

**Comment by iRuxu** [comment]
## 互动 - 删除

这个删除，注意是 

+ 【主楼主isAuthor（可以自己定义）】或【编辑以上User.isEditor】可以删除自己帖子的跟帖或回复。
+ 【层主】或【编辑以上】可以删除自己的楼层的回复

请 @flyflyknife 回复接口在此处，确认权限实装正常。

前端注意弹出2次popover确认


- [x] 已完成

**Comment by iRuxu** [comment]
## 互动 - 举报

任何登录用户均可用本功能

举报直接弹一个$prompt让填理由即可。

直接自动为用户创建一个工单，接口见 https://www.jx3box.com/dashboard/feedback

来源：官网
类型：举报
地址：帖子地址
内容：自动拼接`魔盒论坛《$帖子标题》的$n楼$某某某` + `$用户提交的说辞`

- [x] 已完成

**Comment by iRuxu** [comment]
## 互动 - 拉黑

任何登录用户均可用本功能

进行一个二次确认，使用这里的接口 https://www.jx3box.com/dashboard/privacy?tab=blacklist

自动添加名单

- [x] 已完成

**Comment by iRuxu** [comment]
## 互动 - 黑洞

黑洞的原理，就是这个回复只有那个层主自己能看见，其它人则看不见了，包括管理！

请 @flyflyknife 回复接口到本处

前端注意增加tooltip：`拉入黑洞后仅层主自己可见`

权限：
+ 【主楼主isAuthor（可以自己定义）】或【编辑以上User.isEditor】可以黑洞自己帖子的跟帖或回复。
+ 【层主】或【编辑以上】可以黑洞自己的楼层的回复

- [ ] 已完成

**Comment by iRuxu** [comment]
## 海报

<img width="344" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/acfad6d0-256c-470c-b929-9901366bb489">

这里参考和文章一样实装
取source_type=community的部分即可

- [x] 已完成

**Comment by iRuxu** [comment]
## 面包屑

<img width="580" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/bd71c09f-3b65-4a75-b67f-7c0aa982a7a4">

这里变成魔盒论坛，地址/community

- [x] 已完成

**Comment by iRuxu** [comment]
## 图标
<img width="281" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/415f38db-641a-4092-ac9c-ceffa135024e">

用publish同款图标即可

- [x] 已完成

**Comment by iRuxu** [comment]
## 回复
<img width="721" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/2d3bb83a-8424-4b12-ba79-f881b1e0bf91">

<img width="406" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/f505a7ab-b0de-4c08-bc98-60f96038536b">

- [x] 已完成

**Comment by iRuxu** [comment]
## 点赞数回显

<img width="634" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/9b6880c8-5c60-4501-ad23-28f15c63b4c0">

可以通过批量接口回显
见骚话列表页

- [ ] 已完成

**Comment by iRuxu** [comment]
## 互动UI

<img width="612" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/3f2b0299-ef53-4254-94f5-be5132e6f78b">

间距不yi'zh一致

- [x] 已完成

**Comment by iRuxu** [comment]
## 拉黑

<img width="566" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/0991dc2b-5a68-4036-ac68-d527edd6663e">

点击没反应，要做个2次确认。

如果自己不能拉黑自己和举报自己的话，就disabled掉

- [x] 已完成

**Comment by iRuxu** [comment]
## 信息对齐

除上述外

目前就是  点赞  和  黑洞  还需要再进一步等接口？

- [x] 是的
- [ ] 还有其它：

**Comment by iRuxu** [comment]
## 举报

<img width="539" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/566e0846-b695-4c3d-98c8-2238732c0aac">

要设置 来源，来源就取   /community/$id#楼层ID

- [x] 已完成

**Comment by iRuxu** [comment]
## 精选与置顶

<img width="1026" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/14f3c618-53b1-485a-b3dc-638ae9c3c68b">

列表和详情，补精选和置顶样式，催更冰块

- [x] 已完成

**Comment by Moch1ce** [comment]
api/cms/upload 接口 本地开发环境 提示没有访问权限 这个需要设置什么吗 （测试环境是好的）
![image](https://github.com/JX3BOX/bbs/assets/27264322/a77c1eca-8f77-4089-946c-3c20e1afd7bf)


curl 'https://cms.jx3box.com/api/cms/upload' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryN6xBxgDyWWXSYXtc' \
  -H 'origin: http://localhost:8080' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: http://localhost:8080/' \
  -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryN6xBxgDyWWXSYXtc\r\nContent-Disposition: form-data; name="file"; filename="头像.jpg"\r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundaryN6xBxgDyWWXSYXtc--\r\n'

**Comment by Moch1ce** [comment]
> ## 举报
> <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/8476969/330058046-566e0846-b695-4c3d-98c8-2238732c0aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTE1ODksIm5iZiI6MTcxNTYxMTI4OSwicGF0aCI6Ii84NDc2OTY5LzMzMDA1ODA0Ni01NjZlMDg0Ni1iNjk1LTRjM2QtOThjOC0yMjM4NzMyYzBhYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTQ0MTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjlmZGQ2MWMxMGM5OGIyMWU2MTRmZTMxNDNkNDVmMTUzZTk5NmJiNDkxZDA3ZTQ1NDUwZWVkNTM2ZjZhZGNkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LIj6MXgDKXtOPIzPo1TbwLzIbzfj5FxzZWiWHvsqx5o">
> 要设置 来源，来源就取 /community/$id#楼层ID
> 
> * [x]  已完成


<img width="699" alt="image" src="https://github.com/JX3BOX/bbs/assets/27264322/60b3fdb6-b27d-403b-b9f4-5b7eaf572965"> 这个来源我写在content里了 应该不是写在type里吧

**Comment by iRuxu** [comment]
> api/cms/upload 接口 本地开发环境 提示没有访问权限 这个需要设置什么吗 （测试环境是好的） ![image](https://private-user-images.githubusercontent.com/27264322/330084213-a77c1eca-8f77-4089-946c-3c20e1afd7bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY1MTMsIm5iZiI6MTcxNTYyNjIxMywicGF0aCI6Ii8yNzI2NDMyMi8zMzAwODQyMTMtYTc3YzFlY2EtOGY3Ny00MDg5LTk0NmMtM2MyMGUxYWZkN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMDhlNGM1MTc4YTA5NzFhYzA0ZjNjYmJiZWUzMjQzY2QyYThlNDZkZmZhYjI4MGQ2YjQ0ZmNjOGE0Yjk1NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wBdXfPflANAS8VPGGoF6Mf7rxqNFvnSmoQI8Bz4CHu0)
> 
> curl 'https://cms.jx3box.com/api/cms/upload' -H 'accept: _/_' -H 'accept-language: zh-CN,zh;q=0.9' -H 'cache-control: no-cache' -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryN6xBxgDyWWXSYXtc' -H 'origin: http://localhost:8080' -H 'pragma: no-cache' -H 'priority: u=1, i' -H 'referer: http://localhost:8080/' -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' -H 'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "macOS"' -H 'sec-fetch-dest: empty' -H 'sec-fetch-mode: cors' -H 'sec-fetch-site: cross-site' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' --data-raw $'------WebKitFormBoundaryN6xBxgDyWWXSYXtc\r\nContent-Disposition: form-data; name="file"; filename="头像.jpg"\r\nContent-Type: image/jpeg\r\n\r\n\r\n------WebKitFormBoundaryN6xBxgDyWWXSYXtc--\r\n'

问醉栩

- [x] 已完成

**Comment by iRuxu** [comment]
> ## 举报
> <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/8476969/330058046-566e0846-b695-4c3d-98c8-2238732c0aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY1MTMsIm5iZiI6MTcxNTYyNjIxMywicGF0aCI6Ii84NDc2OTY5LzMzMDA1ODA0Ni01NjZlMDg0Ni1iNjk1LTRjM2QtOThjOC0yMjM4NzMyYzBhYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTg1MDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdiNzk4ZWY3MGE3ZmFkY2Q2NzA1YWM2YjM3MGFlZjExZjljZmIyMTRhYzRhOWRhMGY0YjAzZjIzY2M2N2UxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Jj5GYTcKhUfEWYbU3I3pqaapKtvrko5qLi49Jy5zT0E">
> 要设置 来源，来源就取 /community/$id#楼层ID
> 
> * [x]  已完成

并不是，是有一个字段就叫`refer`

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1888" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/6e5f4468-9b55-4984-928b-aad0c00baa1e">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="1741" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/a66f712a-adca-47c3-9cf9-9428363f3c60">

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="466" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/48efd714-1b48-4278-89a5-bb19a5d0e298">

- [x] 已完成

**Comment by Moch1ce** [comment]
> <img alt="image" width="1741" src="https://private-user-images.githubusercontent.com/8476969/330174162-a66f712a-adca-47c3-9cf9-9428363f3c60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjQzNjAsIm5iZiI6MTcxNTg2NDA2MCwicGF0aCI6Ii84NDc2OTY5LzMzMDE3NDE2Mi1hNjZmNzEyYS1hZGNhLTQ3YzMtOWNmOS05NDI4MzYzZjNjNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTI1NDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk1MzRhNGQ5ZWMxNzk1YmU5YjllMDY5ZjAxMzAwYWMzZmViOGRiMjcxMmYxNmJjNTdjZGI2OTdiYzdkYzFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3_RaDxVYDMV8NQKDsUNFhARV-fGliFeNT2wOb_2-UaI">
> * [ ]  已完成


- [ ] @flyflyknife  这个应该需要一个新的接口，目前的接口只有删我我的帖子 与 回复。

**Comment by iRuxu** [comment]
<img width="389" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/2a0491d6-2a6d-45e5-8c31-4aa3afa53d96">

- [x] 已完成
