### ISSUE TITLE
帖子卡片

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/bbs#99]
## 概念
<img width="654" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/7f33b55d-fbeb-440e-b7e1-2bfabbdf92d8">

我们有些主题比如 “帕鲁”其实存在广告性质。

可以让用户花积分购买论坛卡片主题，购买一张则消耗一张。

- [ ] 已了解

**Comment by iRuxu** [comment]
## 积分商城

<img width="321" alt="image" src="https://github.com/JX3BOX/bbs/assets/8476969/447048f0-ef3f-4377-b70a-5c473e84a3dc">

放到虚拟 = 其它中。

- [x] 已完成

**Comment by iRuxu** [comment]
## 设计

设计先出不少于7款吧，红橙黄绿青蓝紫？

- [ ] 已完成

**Comment by iRuxu** [comment]
## 逻辑与接口

@flyflyknife 

1. 提供一个商城上架逻辑，方便子璇去上架设计师做好的部分。
2. 用户购买了后，增加了对应的商品数量。
3. 用户在发帖（非回帖，仅主题）后，可以根据自己已经购买的卡片，选择一个作为装饰，此时实际上就是给帖子增加一个decoration的字段，然后来设置该字段。注意https://github.com/JX3BOX/os/issues/162 管理的接口也需要支持此设置。

- [x] 已完成

**Comment by iRuxu** [comment]
## 前端

实装该逻辑

- [x] 已完成

**Comment by iRuxu** [comment]
这里的设计方案和普通的装扮不一致。
这里的论坛卡片是独立的，即用一个少一个。
可能需要反复多次购买的
@flyflyknife 

- [x] 已完成

**Comment by flyflyknife** [comment]
> ## 逻辑与接口
> 
> @flyflyknife
> 
>     1. 提供一个商城上架逻辑，方便子璇去上架设计师做好的部分。
> 
>     2. 用户购买了后，增加了对应的商品数量。
> 
>     3. 用户在发帖（非回帖，仅主题）后，可以根据自己已经购买的卡片，选择一个作为装饰，此时实际上就是给帖子增加一个decoration的字段，然后来设置该字段。注意[论坛前台管理 os#162](https://github.com/JX3BOX/os/issues/162) 管理的接口也需要支持此设置。
> 
> 
>     * [x]  已完成

--------------------------

商场上架逻辑和普通的主题装扮一致。注意一点！！！！：在创建商品的库存时，针对可消耗的虚拟装扮，需要新增一个 `is_consumables_of_virtual` 字段提交，把其值设置为 1 。 具体见创建库存接口：

https://swagger.jx3box.com/swagger.html?urls.primaryName=mall.jx3box.com#/%E8%99%9A%E6%8B%9F%E5%95%86%E5%93%81%E7%9A%84%E5%BA%93%E5%AD%98%E7%AE%A1%E7%90%86/VirtualGoods-Create

![图片](https://github.com/JX3BOX/bbs/assets/68375170/23079136-6d67-4581-a885-83cab7b74d54)





在用发帖时，数据增加 一个 decoration_id 字段：

见接口：

https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_Create

![图片](https://github.com/JX3BOX/bbs/assets/68375170/e3d25c04-cf7f-40cc-9428-be60e6706580)


以便后台判断用户是否拥有该装扮。 在数据返回时，会增加 decoration 字段，返回装扮的 type, val 值。 具体见 创建主题帖和主题帖列表

另外还有一个独立的切换主题帖接口

- https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E6%88%91%E7%9A%84-%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96/Discussion_SwitchMyTopicDecoration

注意： 使用装扮和切换装扮都会减少 卡片的装扮数量， 当卡片装扮数量 为0 时，发帖将失败。


注意： 用户装扮表 增加一个 `amount` 字段，用来表示 `当前拥有的消耗品类型的装扮数量`，在获取用户卡片装扮时可以显示该字段，以便用户可以知道当前的剩余数量。为0时，前端提示不允许使用
